name: Pipeline CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testar:
    runs-on: ubuntu-latest
    timeout-minutes: 15  

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  
          cache: "poetry"  

      - name: Instalar Poetry
        run: pip install poetry==1.7.0

      - name: Adicionar Poetry ao PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências
        run: poetry install --no-interaction --no-ansi

      - name: Rodar migrações (se necessário)
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
        run: |
          poetry run alembic upgrade head || echo "Nenhuma migração encontrada"

      - name: Rodar testes com cobertura
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
        run: |
          poetry run pytest -v --cov=./ --cov-report=xml
          
      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v3
        if: success()
