---
name: CI Pipeline

on:
  push: true
  pull_request: true
  branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "test_db"
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: pip install poetry==1.7.0

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run tests
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
        run: poetry run pytest -v --cov=.
